volumes:
  db_data:

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: B6ikxmJ3
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql
